---
title: "La réforme de l'église"
description: "Un extrait de **History of Western Philosophy** de Bertrand Russell."
date: 2021-02-14
categories: ["FR", "Phil"]
draft: false
---

Le début de la réforme d'église remonte à la fondation de l'abbaye de
Cluny en 910 par Guillaume le Pieux, Duc d'Aquitaine. Cette abbaye
était, dès son début, indépendante de toute l'autorité externe sauf
celle du pape ; et par ailleurs, son abbé était donné l'autorité sur les
autres monastères à laquelle doivent ses origines.

La plupart de monastères, à ce temps, étaient riches et laxistes ;
Cluny, tout en évitant l'ascétisme extrême, a pris soin à préserver la
décence et le décorum.

Le deuxième abbé, Odo, était allé à l'Italie, et lui fait donner le
contrôle de plusieurs églises romaines. Il n'a pas toujours réussi.
L'abbaye de Farfa, divisée par un schisme entre deux abbés rivaux qui
ont de surcroît assassiné ses prédécesseurs, a résisté l'introduction de
moines Cluniacs par Odo, et a débarrassé par empoisonnement l'abbé que
Albéric a installé par force armée, Albéric étant le dirigeant de Rome
qui a invité Odo.

Dans la douzième siècle la zèle de réforme de Cluny s'était peu à peu
diminuée. Saint-Bernard a fait des objections à ses architectures fines
; à l'instar de tous les hommes honnêtes de son temps, il considère les
édifices ecclésiastiques splendides un symbole de la fierté impie.
